#!/usr/bin/env bash
# Copyright (C) 2026 Parity Technologies (UK) Ltd.
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Generate an index.html page linking to all benchmark comparison reports.
#
# Usage:
#   ./generate_index.sh [reports_dir]
#
# Default reports_dir: ../results/reports (relative to this script)
# Output: index.html in the reports directory
#
# Run this after compare_runs.sh to create a front page for GitHub Pages.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPORTS_DIR="${1:-$SCRIPT_DIR/comparison-reports}"

if [ ! -d "$REPORTS_DIR" ]; then
    echo "Error: reports directory not found: $REPORTS_DIR"
    exit 1
fi

INDEX="$REPORTS_DIR/index.html"

# Collect all HTML reports (exclude index.html itself)
REPORTS=()
while IFS= read -r -d '' f; do
    name=$(basename "$f")
    [ "$name" = "index.html" ] && continue
    REPORTS+=("$name")
done < <(find "$REPORTS_DIR" -maxdepth 1 -name '*.html' -print0 | sort -z)

if [ ${#REPORTS[@]} -eq 0 ]; then
    echo "No HTML reports found in $REPORTS_DIR"
    exit 1
fi

# Generate index.html
cat > "$INDEX" <<'HEADER'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Benchmark Reports — polkadot-rest-api vs sidecar</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, monospace;
    background: #0d1117; color: #c9d1d9; padding: 40px 24px; max-width: 900px; margin: 0 auto;
  }
  h1 { text-align: center; color: #e6edf3; margin-bottom: 8px; font-size: 1.6em; }
  .subtitle { text-align: center; color: #8b949e; margin-bottom: 32px; font-size: 0.9em; }
  .reports { list-style: none; }
  .reports li {
    background: #161b22; border: 1px solid #30363d; border-radius: 8px;
    margin-bottom: 12px; transition: border-color 0.2s;
  }
  .reports li:hover { border-color: #58a6ff; }
  .reports li a {
    display: flex; align-items: center; padding: 16px 20px;
    color: #c9d1d9; text-decoration: none; gap: 16px;
  }
  .reports li a:hover { color: #e6edf3; }
  .icon { font-size: 1.4em; }
  .info { flex: 1; }
  .info .name { font-size: 1.05em; font-weight: 600; color: #58a6ff; }
  .info .detail { font-size: 0.8em; color: #8b949e; margin-top: 4px; }
  .info .detail .endpoint { color: #3fb950; font-weight: 600; }
  .info .detail .scenario { color: #d29922; font-weight: 600; }
  .arrow { color: #484f58; font-size: 1.2em; }
  .meta { text-align: center; color: #484f58; font-size: 0.75em; margin-top: 32px; }
</style>
</head>
<body>
<h1>Benchmark Reports</h1>
<p class="subtitle">polkadot-rest-api vs substrate-api-sidecar</p>
<ul class="reports">
HEADER

for report in "${REPORTS[@]}"; do
    # Parse endpoint and scenario from filename: comparison_<endpoint>_<scenario>.html
    base="${report%.html}"
    base="${base#comparison_}"

    # Extract scenario (last known scenario name)
    scenario=""
    endpoint="$base"
    for s in light_load medium_load heavy_load stress_test; do
        if [[ "$base" == *"_${s}" ]]; then
            scenario="$s"
            endpoint="${base%_${s}}"
            break
        fi
    done

    # Format for display
    endpoint_display="${endpoint//_/ }"
    scenario_display="${scenario//_/ }"

    cat >> "$INDEX" <<EOF
  <li>
    <a href="$report">
      <span class="icon">📊</span>
      <div class="info">
        <div class="name">$endpoint_display</div>
        <div class="detail">
          Endpoint: <span class="endpoint">$endpoint</span>
EOF

    if [ -n "$scenario" ]; then
        cat >> "$INDEX" <<EOF
          &nbsp;&bull;&nbsp; Scenario: <span class="scenario">$scenario_display</span>
EOF
    fi

    cat >> "$INDEX" <<EOF
        </div>
      </div>
      <span class="arrow">→</span>
    </a>
  </li>
EOF
done

cat >> "$INDEX" <<'FOOTER'
</ul>
<p class="meta">
  Generated by generate_index.sh |
FOOTER

echo "  $(date +%Y-%m-%d\ %H:%M:%S)" >> "$INDEX"

cat >> "$INDEX" <<'FOOTER2'
</p>
</body>
</html>
FOOTER2

echo "Generated: $INDEX (${#REPORTS[@]} reports)"
